name: aae
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.1
  - python=3.7.0
  - tensorboard=2.1.1
  - tensorflow=2.1.0  